# Generated by Django 4.1 on 2023-07-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_alter_worker_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='first_name',
            field=models.CharField(default='John', max_length=255),
        ),
        migrations.AlterField(
            model_name='worker',
            name='last_name',
            field=models.CharField(default='Doe', max_length=255),
        ),
    ]
