# Generated by Django 4.1 on 2023-07-21 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_alter_tasktype_name_alter_worker_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'ordering': ['username']},
        ),
    ]
