# Generated by Django 4.1 on 2023-07-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_alter_worker_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='email',
            field=models.EmailField(default='johndoe@example.com', max_length=255),
        ),
    ]
