# Generated by Django 4.1 on 2023-07-23 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0005_alter_worker_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='email',
            field=models.EmailField(default='johndoe@example.com', max_length=255, null=True),
        ),
    ]
